version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    image: dms-calendar-bot:latest
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
